[package]
name = "tokenizers"
version = "0.1.3"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.4"
tokenizers = "0.13.2"

[profile.release]
strip = true
